version: "3.9"

services:
  api:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platzi-conf-store-strapi-api
    volumes: 
      - ".:/srv/app"
    ports:
      - "1338:1337"